version: "3.7"
services:
  robot:
    build:
      context: .
      dockerfile: "Dockerfile.${ROBOT_LIBRARY:-Browser}"
    volumes:
      - "./examples/${ROBOT_LIBRARY:-Browser}:/home/pwuser/source:ro"
      - "./logs:/home/pwuser/logs"
    environment:
      ROBOT_RUN_MODE: "watch"  # watch, button or anything/none for once
    ports:
      - 6080:6080
      - 10081:10081
    shm_size: 2g
    security_opt:
      - label=disable
